### ISSUE TITLE
caddy fails on first request when using caddy-datadog plugin

### ISSUE THREAD

**Issue by pietvanzoen** [payintech/caddy-datadog#1]
Hi! I'm trying to setup caddy-datadog but I'm running into an issue where caddy exits on first request when caddy-datadog is turned on. I can't figure out what's happening from the logs. 

If you have any ideas/insight it would be appreciated!

I installed caddy via `curl https://getcaddy.com | bash -s http.datadog`.

My caddy version is `0.10.6`.

I'm running caddy on raspbian jessie.

Caddyfile
```
pietvanzoen.com {
  root  /var/www/pietvanzoen.com
  datadog
  tls ***@***.com {
    protocols  tls1.0 tls1.2
  }
  log / stdout "{combined}"
  gzip
  errors stderr {
    404 404.html # Not Found
  }
  rewrite /feed /feed.xml
}
```

Log output:
```
caddy:  Activating privacy features... done.
caddy:  https://pietvanzoen.com
caddy:  2017/08/11 09:05:22 https://pietvanzoen.com
caddy:  http://pietvanzoen.com
caddy:  2017/08/11 09:05:22 http://pietvanzoen.com
caddy:  11/Aug/2017:09:05:28 +0000 [PANIC /] /usr/local/go/src/sync/atomic/asm_linux_arm.s:109 - runtime error: invalid memory address or nil pointer dereference
caddy:  37.153.200.99 - - [11/Aug/2017:09:05:28 +0000] "GET / HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
caddy:  11/Aug/2017:09:05:29 +0000 [PANIC /] /usr/local/go/src/sync/atomic/asm_linux_arm.s:109 - runtime error: invalid memory address or nil pointer dereference
caddy:  37.153.200.99 - - [11/Aug/2017:09:05:29 +0000] "GET / HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
caddy:  panic: runtime error: invalid memory address or nil pointer dereference
caddy:  [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11528]
caddy:  goroutine 6 [running]:
caddy:  sync/atomic.addUint64(0x10c129bc, 0x0, 0x0, 0x0, 0x0)
caddy:  /usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
caddy:  github.com/payintech/caddy-datadog.initializeDatadogHQ.func2(0x10d9a180)
caddy:  src/github.com/payintech/caddy-datadog/datadog.go:241 +0x4d4
caddy:  created by github.com/payintech/caddy-datadog.initializeDatadogHQ
caddy:  src/github.com/payintech/caddy-datadog/datadog.go:254 +0x7e0
systemd:  caddy.service: main process exited, code=exited, status=2/INVALIDARGUMENT
systemd:  Unit caddy.service entered failed state.
```

**Comment by pietvanzoen** [comment]
ps. thanks for setting up the plugin! hope i can get this working :)

**Comment by thibaultmeyer** [comment]
Hello,

Have you try to put the complete configuration ?

```
datadog {
    statsd    127.0.0.1:8125
}
```

**Comment by pietvanzoen** [comment]
Unfortunately no change.

I'm poking around caddy issues and found this: https://github.com/mholt/caddy/issues/1788

And the resulting fix they implemented for `fastcgi` here: https://github.com/mholt/caddy/pull/1789/commits/dd3f460cf8bc63a33301698eec07825fd3808117

They reference a known go bug: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned.

I'm not super familiar with Go so I'm guessing here... but could it be related to this struct?: https://github.com/payintech/caddy-datadog/blob/master/datadog.go#L51

**Comment by thibaultmeyer** [comment]
It's a very strange issue. I have applied the same patch as `fastcgi`(https://github.com/mholt/caddy/pull/1789/commits/dd3f460cf8bc63a33301698eec07825fd3808117) and published the new version on Caddy website.

Could you try to download again Caddy server with the new plugin version ?

**Comment by pietvanzoen** [comment]
All good! Thanks for quick responses. 

A very strange bug indeed.
